config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
# frozen_string_literal: true

# app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORIES = %w[chinese italian japanese french belgian].freeze
  validates :name, presence: true
  validates :address, uniqueness: true, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
# frozen_string_literal: true

# app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

# app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

# app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def show; end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
      <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
      <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |r| %>
  <%= r.error_notification %>

  <div class='form-group'>
    <%= r.label :name %>
    <%= r.text_field :name, class: 'form-control' %>
  </div>
  <p></p>
  <div class='form-group'>
    <%= r.label :category %>
    <%= r.text_field :category, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= r.submit class: 'btn btn-danger' %>
  </div>
  <div class='row m-1'>
    <%= link_to restaurants_path do %>
    <i class='fa fa-hand-o-left' aria-hidden='true'> Back To Restaurants List</i>
    <% end %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class='container'>
  <h1>Edit Restaurant <%= @restaurant.name %></h1>
  <%= render 'restaurants/form' %>
</div>

app/views/restaurants/index.html.erb
<!-- app/views/restaurants/index.html.erb -->
<div class='container'>
  <div class='card p-2 text-center bg-light'>
    <h1>Restaurants</h1>
  </div>
    <div>
      <p></p>
      <%= link_to new_restaurant_path do %>
      <i class='fas fa-utensils' aria-hidden='true'> Add a New Restaurant</i>
      <% end %>
    </div>
    <% @restaurants.each do |restaurant| %>
      <div class='card mt-2 p-4'>
        <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
        <p></p>
        <h4><%= restaurant.category %></h4>
        <p><%= restaurant.address %></p>
        <p><%= restaurant.phone_number %></p>
      </div>
    <% end %>
</div>

app/views/restaurants/new.html.erb
<div class='container'>
  <h1>Add a New Restaurant</h1>
  <%= render 'restaurants/form' %>
</div>

<form action='/restaurants' method='post'>
</form>

app/views/restaurants/show.html.erb
<div class='container p-2'>
  <div class='row my-4 m-1'>
    <h1><%= @restaurant.name %></h1>
  </div>
  <div class='card bg-light p-2'>
    <h4><%= @restaurant.category %></h4>
    <p></p>
    <p><%= @restaurant.address %></p>
    <p><%= @restaurant.phone_number %></p>
  </div>
  <%= link_to 'Add a review', new_restaurant_review_path(@restaurant) %>
  <%= @restaurant.reviews.each do |review| %>
    <div class='card bg-light p-2'>
      <p><%= review.content %></p>
      <p><%= review.rating %></p>
    </div>
  <% end %>
  <p></p>
  <div class='row m-1'>
    <%= link_to restaurants_path do %>
    <i class='fa fa-hand-o-left' aria-hidden='true'> Back To Restaurants List</i>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<!-- # app/views/reviews/new.html.erb -->

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit 'Add Review', class: 'btn btn-primary' %>
<% end %>

app/views/reviews/show.html.erb
<div class='container p-2'>
  <div class='row my-4 m-1'>
    <h1>Reviews</h1>
  </div>
  <div class='card bg-light p-2'>
    <h4><%= @review.content %></h4>
    <p></p>
    <p><%= @review.rating %></p>
  </div>
  <p></p>
  <div class='row m-1'>
    <%= link_to restaurant_path(restaurant) %>
    <i class='fad fa-taco' aria-hidden='true'> Back To Restaurant Page</i>
  <div class='row m-1'>
    <%= link_to restaurants_path do %>
    <i class='fa fa-hand-o-left' aria-hidden='true'> Back To Restaurants List</i>
    <% end %>
  </div>
</div>